#!/bin/sh

name=$(basename -- "$0")
data_dir="${XDG_DATA_HOME:-$HOME/.local/share}/dwmstatus/${name}"
text="${data_dir}/text"
clock=$(date '+%I')

case "$clock" in
        "00") icon="🕛" ;;
        "01") icon="🕐" ;;
        "02") icon="🕑" ;;
        "03") icon="🕒" ;;
        "04") icon="🕓" ;;
        "05") icon="🕔" ;;
        "06") icon="🕕" ;;
        "07") icon="🕖" ;;
        "08") icon="🕗" ;;
        "09") icon="🕘" ;;
        "10") icon="🕙" ;;
        "11") icon="🕚" ;;
        "12") icon="🕛" ;;
esac

[ -d "${data_dir}" ] || mkdir -p "${data_dir}"
date "+%Y %b %d (%a) $icon%I:%M%p" > "${text}"

