#!/bin/sh

name=$(basename -- "$0")
data_dir="${XDG_DATA_HOME:-$HOME/.local/share}/status/${name}"
text="${data_dir}/text"

[ -d "${data_dir}" ] || mkdir -p "${data_dir}"
( ( ping -c1 8.8.8.8 > /dev/null && echo -n 🌐 ) || echo -n ❎ ) > "${text}"
